# Generated by Django 5.2.4 on 2025-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorNome', models.CharField(max_length=100)),
                ('consultorEmail', models.EmailField(max_length=254, unique=True)),
                ('consultorTelefone', models.CharField(blank=True, max_length=15, null=True)),
                ('consultorAtivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
            },
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contextoConteudo', models.TextField()),
                ('contextoAtivo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contexto',
                'verbose_name_plural': 'Contextos',
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversaEmailCliente', models.EmailField(max_length=254)),
                ('conversaTextoCliente', models.TextField()),
                ('conversaTextoResposta', models.TextField(blank=True, null=True)),
                ('conversaDataHora', models.DateTimeField(auto_now_add=True)),
                ('conversaAtiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametroChave', models.CharField(max_length=100, unique=True)),
                ('parametroValor', models.TextField()),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
            },
        ),
    ]
