# Generated by Django 5.2.4 on 2025-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensagem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='email',
            field=models.EmailField(blank=None, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(blank=None, default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='enviado_por_usuario',
            field=models.BooleanField(default=True, verbose_name='Eviado pelo usuário'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='session_id',
            field=models.CharField(blank=None, default='', max_length=100, verbose_name='Sessão'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(verbose_name='Texto da Mensagem'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da mensagem'),
        ),
    ]
