# Generated by Django 5.2.4 on 2025-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensagem_email_mensagem_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexto',
            name='contextoTitulo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Título do Contexto'),
        ),
        migrations.AlterField(
            model_name='contexto',
            name='contextoAtivo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora mensagem'),
        ),
        migrations.AlterField(
            model_name='contexto',
            name='contextoConteudo',
            field=models.TextField(verbose_name='Conteúdo do Contexto'),
        ),
    ]
