# Generated by Django 5.2.4 on 2025-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contexto_contextotitulo_alter_contexto_contextoativo_and_more'),
    ]

    operations = [

    ]
