# Generated by Django 5.2.4 on 2025-07-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contexto_contextoativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexto',
            name='contextoAtivo',
        ),
        migrations.AddField(
            model_name='contexto',
            name='contextoAtual',
            field=models.BooleanField(default=False, verbose_name='Atual'),
        ),
    ]
