# Generated by Django 5.2.4 on 2025-07-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contexto_contextoativo_contexto_contextoatual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexto',
            name='contextoAtivo',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora de Ativação'),
        ),
    ]
