# Generated by Django 5.2.4 on 2025-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contexto_contextoativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='completion_tokens',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tokens de Conclusão'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='custo_estimado',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10, null=True, verbose_name='Custo Estimado'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tokens de Prompt'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='total_tokens',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tokens Totais'),
        ),
    ]
