# Generated by Django 5.2.4 on 2025-07-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mensagem_completion_tokens_mensagem_custo_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultor',
            name='consultorAtivo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='consultorEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='consultorNome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='consultor',
            name='consultorTelefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadNome', models.CharField(max_length=100, verbose_name='Nome')),
                ('leadEmail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('leadTelefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('leadDataHoraCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora criação do lead')),
                ('leadAtivo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('leadIntegrado', models.BooleanField(default=False, verbose_name='Integrado com CRM')),
                ('leadConsultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.consultor', verbose_name='Consultor')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
