# Generated by Django 5.2.4 on 2025-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_consultor_consultorativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnidadeNome', models.CharField(max_length=100, verbose_name='Unidade')),
                ('UnidadeEndereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('UnidadeAtiva', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
